pipeline:
  identifier: Build_failing_pipeline_1698404611859
  name: Build failing-pipeline
  orgIdentifier: default
  projectIdentifier: Test_Pipelinr
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698387505960
        repoName: failing-pipeline
  stages:
    - stage:name: Print welcome message
      identifier: welcome_message
      type: CI
      spec:
        cloneCodebase: true
        platform:
          os: Linux
          arch: Amd64
        runtime:
          type: Cloud
          spec: {}
        execution:
          steps:
            - step:
                type: Run
                name: Welcome
                identifier: Welcome
                spec:
                  connectorRef: my_docker_hub
                  image: alpine
                  shell: Sh
                  command: Echo "Welcome to Harness CI"
