pipeline:
  identifier: Build_failing_pipeline_1698404611859
  name: Build failing-pipeline
  orgIdentifier: default
  projectIdentifier: Test_Pipelinr
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698387505960
        repoName: failing-pipeline
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: exit 0;
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          sharedPaths:
            - ""
          caching:
            enabled: false
            paths: []
        type: CI
